---
# tasks file for solr

- name: Cleanup solr
  include_tasks: clean.yml
  when: solr_clean

- name: Set facts
  include_tasks: set_facts.yml

- name: Setup prereqs
  include_tasks: prereqs.yml

- name: Setup tuning settings
  include_tasks: tuning.yml

- name: Run setup
  include_tasks: setup.yml

- name: Install solr
  include_tasks: install.yml

- name: Setup solr
  include_tasks: config.yml

- name: Setup solr services
  include_tasks: service.yml

- name: Wait for solr services
  include_tasks: wait.yml

- name: Setup solr collections
  include_tasks: collections.yml
